{{  
exports.publishOn = new Date().toString()
}}

POST HTTP://localhost:3000/posts
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM3LCJlbWFpbCI6Im1hcmtkb2UxMjNAZ21haWwuY29tIiwiaWF0IjoxNzMwMjgxMjM1LCJleHAiOjE3MzAyODQ4MzUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.5Yu_xAGmaZwLXdpxgbFR9yhGdtEN817FJdZ_sl6VhcM

{
    "title":"What's new with NestJS",
    "postType":"post",
    "slug":"new-with-nestjs91",
    "status": "draft",
    "content": "test content",
    "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",

    "featuredImageURL": "https://unsplash.com/photos/people-sitting-at-the-table-2pPw5Glro5I",
    //"publishOn": "{{publishOn}}",
    //"tags":["nestjs","typescript"],
    //"metaoptions":[{"key":"testkey","value":20}]
    "metaoptions":{
    "metaValue":"{ \"sidebarEnabled\":true,\"footerActive\":true}"
    },
    //"authorId":12,
    "tags":[1,3]
}